name: ml-reproducibility
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - accelerate
  - black
  - huggingface_hub
  - ipykernel
  - jupyter-black
  - lightning
  - matplotlib
  - mlflow
  - pandas
  - pytorch-gpu
  - scikit-learn
  - tensorboard
  - torchinfo
  - torchvision
  - tqdm
  - transformers
  - pip:
    - git+https://github.com/americanexpress/mlflow-server-proxy