dataset:
  datamodule: MNISTDataModule
  batch_size: 64
optimizer:
  type: AdamW
  lr: 0.001
outputs:
  output_dir: outputs
training:
  num_epochs: 10
model:
  model_type: SimpleMLP
  num_hidden_units:
  - 20